security:
    enable_authenticator_manager: true
    password_hashers:
        Sonata\UserBundle\Model\UserInterface: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
        sonata_user_bundle:
            id: sonata.user.security.user_provider
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_SONATA_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            lazy: true
            pattern: /admin(.*)
            provider: sonata_user_bundle
            context: user
            form_login:
                login_path: sonata_user_admin_security_login
                check_path: sonata_user_admin_security_check
                default_target_path: sonata_admin_dashboard
            logout:
                path: sonata_user_admin_security_logout
                target: sonata_user_admin_security_login
        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: ^/admin/login, role: PUBLIC_ACCESS }
        - { path: ^/admin/logout, role: PUBLIC_ACCESS }
        - { path: ^/admin/login_check, role: PUBLIC_ACCESS }
        - { path: ^/admin/request, role: PUBLIC_ACCESS }
        - { path: ^/admin/check-email, role: PUBLIC_ACCESS }
        - { path: ^/admin/reset/.*, role: PUBLIC_ACCESS }

        - { path: ^/admin, roles: ROLE_ADMIN }