sonata_admin:
    title: 'Sonata Admin'
    options:
        list_action_button_content: icon
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
            -
                type: sonata.block.service.text
                position: right
                settings:
                    template: Sonata/telegram.html.twig

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
