parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Admin\DocumentAdmin:
        arguments: [ ~, App\Entity\Document,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Documents }

    App\Admin\CounterpartyAdmin:
        arguments: [ ~, App\Entity\Counterparty,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Counterparties }

    App\Admin\InstrumentGroupAdmin:
        arguments: [ ~, App\Entity\InstrumentGroup,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Instrument Group }

    App\Admin\InstrumentNameAdmin:
        arguments: [ ~, App\Entity\InstrumentName,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Instrument Name }

    App\Admin\PhoneAdmin:
        arguments: [ ~, App\Entity\Phone,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Phones }

    App\Admin\PlaceOfUseAdmin:
        arguments: [ ~, App\Entity\PlaceOfUse,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Places Of Use }

    App\Admin\RentAdmin:
        arguments: [ ~, App\Entity\Rent,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Rents }

    App\Admin\StorageAdmin:
        arguments: [ ~, App\Entity\Storage,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Storages }

    App\Admin\SubdivisionAdmin:
        arguments: [ ~, App\Entity\Subdivision,~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Rent Control, label: Subdivisions }
